- name: "Internet"
  description: "Internet software"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - firefox-i18n-$LOCALE
    - chromium
    - brave
    - opera
    - qutebrowser
    - tor-browser
    - hexchat
    - telegram-desktop
    - pidgin
    - falkon
    - filezilla
    - geary
    - deluge
    - qbittorrent
    - thunderbird
    - transmission-gtk
    - ktorrent
    - insync
- name: "Terminals"
  description: "Terminals"
  critical: false
  hidden: false
  selected: false
  packages:
    - alacritty
    - gnome-terminal
    - guake
    - kitty
    - konsole
    - lxterminal
    - sakura
    - termite
    - terminator
    - tilix
    - tilda
- name: "File Manager"
  description: "Filemanager"
  critical: false
  hidden: false
  selected: false
  packages:
    - caja
    - dolphin
    - nautilus
    - nemo
    - nemo-fileroller
    - pcmanfm
- name: "Password Manager"
  description: "Password manager"
  critical: false
  hidden: false
  selected: false
  packages:
    - bitwarden-bin
    - enpass-bin
    - keepassxc
    - lastpass
- name: "Fonts"
  description: "Fonts"
  critical: false
  hidden: false
  selected: false
  packages:
    - terminus-font
    - noto-fonts-emoji
- name: "Dev Tools"
  description: "Development"
  critical: false
  hidden: false
  selected: false
  packages:
    - code
    - neovim
    - emacs
    - gitahead-bin
    - gitg
    - gitfiend
    - gitkraken
- name: "Graphics"
  description: "Graphics"
  critical: false
  hidden: false
  selected: false
  packages:
    - blender
    - darktable
    - digikam
    - krita
    - pinta
- name: "Usb"
  description: "Usb"
  critical: false
  hidden: false
  selected: false
  packages:
    - etcher-bin
    - imagewriter
    - woeusb
- name: "Virtualbox"
  description: "Install virtualbox"
  critical: false
  hidden: false
  selected: false
  packages:
    - virtualbox
    - virtualbox-host-dkms
- name: "Accessories"
  description: "Accessories"
  critical: false
  hidden: false
  selected: false
  packages:
    - cheese
    - liferea
    - mediainfo
    - mcomix
