#!/bin/bash

init_pacman() {
sudo pacman-key --init
sudo pacman-key --populate
sudo pacman-key --refresh-keys --keyserver hkp://keys.gnupg.net
}

online_method() {
sudo cp -praf /usr/share/calamares/settings-online.conf /usr/share/calamares/settings.conf
sudo cp -praf /usr/share/calamares/modules/packages-online.conf /usr/share/calamares/modules/packages.conf
sudo cp -praf /usr/share/calamares/modules/welcome-online.conf /usr/share/calamares/modules/welcome.conf
}

offline_method() {
sudo cp -praf /usr/share/calamares/settings-offline.conf /usr/share/calamares/settings.conf
sudo cp -praf /usr/share/calamares/modules/packages-offline.conf /usr/share/calamares/modules/packages.conf
sudo cp -praf /usr/share/calamares/modules/welcome-offline.conf /usr/share/calamares/modules/welcome.conf
}

run_calamares() {
  if [[ $(command -v pkexec) ]]; then
    # pkexec --disable-internal-agent "/usr/bin/calamares" "$@"
    bash -c "sudo -E /usr/bin/calamares -d"
  else
    sudo -E /usr/bin/calamares -d
  fi
}

install_method() {
  yad --center --borders=20 \
  --image=dialog-question \
  --title="Installation method" \
  --text="<span font=\"12\">Выберите метод установки\n(Choose installation method)</span>\n" \
  --button="Cancel":0 \
  --button="Online":1 \
  --button="Offline":2
  res=$?

  if [[ $res == 1 ]]; then
    init_pacman
    online_method
    run_calamares
    exit 0
  fi

  if [[ $res == 2 ]]; then
    offline_method
    run_calamares
    exit 0
  fi

  if [[ $res == 0 ]]; then
    exit 0
  fi
}

install_method
