#!/bin/bash

online_method() {
sudo cp -praf /usr/share/calamares/settings-online.conf /usr/share/calamares/settings.conf
sudo cp -praf /usr/share/calamares/modules/packages-online.conf /usr/share/calamares/modules/packages.conf
sudo cp -praf /usr/share/calamares/modules/welcome-online.conf /usr/share/calamares/modules/welcome.conf
}

offline_method() {
sudo cp -praf /usr/share/calamares/settings-offline.conf /usr/share/calamares/settings.conf
sudo cp -praf /usr/share/calamares/modules/packages-offline.conf /usr/share/calamares/modules/packages.conf
sudo cp -praf /usr/share/calamares/modules/welcome-offline.conf /usr/share/calamares/modules/welcome.conf
}

run_calamares() {
  if [[ $(command -v pkexec) ]]; then
    #####! /root/.config/Kvantum
    # exec pkexec env DISPLAY="$DISPLAY" XAUTHORITY="$XAUTHORITY" \
    #   XDG_CURRENT_DESKTOP="$XDG_CURRENT_DESKTOP" \
    #   XDG_SESSION_TYPE="$XDG_SESSION_TYPE" \
    #   dbus-launch /usr/bin/calamares -style kvantum "$@"

    bash -c "sudo -E /usr/bin/calamares -style kvantum -D4"
    # bash -c "sudo -E /usr/bin/calamares -style kvantum -d"
  else
    sudo -E /usr/bin/calamares -style kvantum -d
  fi
}

install_method() {
  yad --center --borders=20 \
  --image=dialog-question \
  --title="Installation method" \
  --text="<span font=\"12\">Выберите метод установки\n(Choose installation method)</span>\n" \
  --button="Cancel":0 \
  --button="Online":1 \
  --button="Offline":2
  res=$?

  if [[ $res == 1 ]]; then
    online_method
    run_calamares
  fi

  if [[ $res == 2 ]]; then
    offline_method
    run_calamares
  fi

  [[ $res == 0 ]] && exit 0
}

install_method
